# Freight Trust TOML Config
# set node data path --data-path=<PATH>

# 	RPC Node
rpc-http-api=["ETH","NET","WEB3","CLIQUE","TXPOOL"]
rpc-http-cors-origins=["http://0xfreight.com","http://remix.ethereum.org","http://freight.sh","http://freight.st","http://freight-chain.com","http://besu.io","http://besu.network","http://freight-stats.com","https://freighttrust.net","https://freighttrust.com","https://freighttrust.io","https://freightauth.com","http://freight-sec.com","http://freight.cx","http://*.freight.sh","http://*freight.st","http://*.besu.io","https://*.freighttrust.net","http://https*.freighttrust.com","http://*.0xfreight.com","http://freightrelay.net","http://*.freight.cx"]

# Graph QL
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port="3680"

# Metrics
metrics-enabled=true
metrics-category=["BLOCKCHAIN","PEERS","PROCESS","RPC"]

# 	Network
bootnodes=["enode://enode://694c9cdd1a95ea242cf194d6e0738c44379446ed59abe1a34763dd48f700a3edf3f849b5b2127d38202583ec17eecee604d15d3c7bf83a86494c26571507400e@54.226.223.85:30305"]

rpc-http-host="0.0.0.0"
rpc-http-port=3678

rpc-ws-host="0.0.0.0"
rpc-ws-port=3679

# Chain
genesis-file="genesis.json" # Path to the custom genesis file
miner-enabled=false